#!/usr/bin/env ruby

require("rb-cmdline")

cmd = Cmdline.new
cmd.add_option("a", "option-a", "value", "a simple option")
cmd.set_option_default("a", "42")
cmd.add_option("b", "", "value", "an short option")
cmd.add_option("", "option-c", "value", "a long option")
cmd.add_flag("d", "flag-d", "a simple flag")
cmd.parse(Cmdline.argv)

printf("a: %s\n", cmd.option_value("a"))

if cmd.is_option_set("b")
  printf("b: %s\n", cmd.option_value("b"))
end

if cmd.is_option_set("option-c")
  printf("option-c: %s\n", cmd.option_value("option-c"))
end

printf("d: %s\n", cmd.is_option_set("d"))
